# Generated by Django 5.1.1 on 2025-11-04 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_expense_user_expense_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_part_no', models.CharField(max_length=100, verbose_name='Shipped Part No.')),
                ('part_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Part Price')),
                ('part_description', models.TextField(verbose_name='Part Description')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
