# Generated by Django 5.1.1 on 2025-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_parttransactionlog_new_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttransaction',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
