# Generated by Django 5.1.1 on 2025-10-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
