# Generated by Django 5.1.1 on 2025-11-12 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=50, unique=True, verbose_name='Call ID')),
                ('source_of_income', models.CharField(max_length=100, verbose_name='Source of Income')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.part', verbose_name='Part No')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.technician', verbose_name='Technician')),
            ],
        ),
    ]
