# Generated by Django 5.1.1 on 2025-11-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_parttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='parttransaction',
            name='part',
        ),
        migrations.AddField(
            model_name='parttransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.CreateModel(
            name='PartTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('part_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Part Price')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='accounts.part', verbose_name='Part No')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.parttransaction', verbose_name='Transaction')),
            ],
        ),
    ]
