# Generated by Django 5.1.1 on 2025-11-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_parttransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttransactionitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
