# Generated by Django 5.1.1 on 2025-11-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_parttransactionitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=10)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
    ]
