# Generated by Django 5.1.1 on 2025-11-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_parttransactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttransactionlog',
            name='new_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parttransactionlog',
            name='old_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
