# Generated by Django 5.1.1 on 2025-11-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_parttransaction_service_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttransactionitem',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='parttransactionitem',
            name='part',
        ),
        migrations.RemoveField(
            model_name='parttransactionlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='PartTransaction',
        ),
        migrations.DeleteModel(
            name='PartTransactionItem',
        ),
        migrations.DeleteModel(
            name='PartTransactionLog',
        ),
    ]
