# Generated by Django 5.1.1 on 2025-11-25 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_transaction_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('serial_no', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
                ('expencer_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AMCIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=200)),
                ('serial_no', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('amc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amc_coverage', models.CharField(blank=True, max_length=20, null=True)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.technician')),
            ],
        ),
    ]
